# Copyright Â© 2022 Gitleaks LLC - All Rights Reserved.
# You may use this code under the terms of the GITLEAKS-ACTION END-USER LICENSE AGREEMENT.
# You should have received a copy of the GITLEAKS-ACTION END-USER LICENSE AGREEMENT with this file.
# If not, please visit https://gitleaks.io/COMMERCIAL-LICENSE.txt.
name: gitleaks
permissions:
  contents: read
concurrency:
  group: gitleaks-${{ github.ref }}
  cancel-in-progress: true
on: [pull_request, push, workflow_dispatch]
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@bf2dc8e55639c1e091e9b45970152e4313705814
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
